spring:
  application:
    name: pass-web
  datasource:                           # docker-compose? ???? DB ?? ?????.
    url: jdbc:mysql://127.0.0.1:3307/pass_local951?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass_local_user951
    password: passlocal123951
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
